Repository SOPT-all/35-SOPKATHON-WEB-web3, pull requests merged in 2024-11, with the labels that each got.

#4 Feat: react-router-dom 설정
  Client/package.json
  Client/src/App.jsx
  Client/src/pages/.keep
  Client/src/pages/CheckRoutine.jsx
  Client/src/pages/List.jsx
  Client/src/pages/Main.jsx
  Client/src/pages/PostRoutine.jsx
  Client/src/pages/index.js
Labels: Feat 🏃🏻‍♀️

#8 Design: 메인뷰 구현
  Client/public/assets/.keep
  Client/public/assets/img_symbol.svg
  Client/public/assets/img_symbol_LB.svg
  Client/public/assets/img_symbol_LT.svg
  Client/public/assets/img_symbol_RB.svg
  Client/public/assets/img_symbol_RT.svg
  Client/src/assets/svg/ImgSymbol.jsx
  Client/src/assets/svg/ImgSymbolLb.jsx
  Client/src/assets/svg/ImgSymbolLt.jsx
  Client/src/assets/svg/ImgSymbolRb.jsx
  Client/src/assets/svg/ImgSymbolRt.jsx
  Client/src/assets/svg/index.jsx
  Client/src/pages/Main.jsx
Labels: Feat 🏃🏻‍♀️

#7 feat: 현재 시간 로컬스토리지 저장
  Client/public/assets/icn_routine_back.svg
  Client/public/assets/img_hair_less02.svg
  Client/public/assets/img_hair_many.svg
  Client/src/assets/svg/IcnRoutineBack.jsx
  Client/src/assets/svg/ImgHairLess02.jsx
  Client/src/assets/svg/ImgHairMany.jsx
  Client/src/assets/svg/index.jsx
  Client/src/components/check/Header.jsx
  Client/src/pages/CheckRoutine.jsx
  Client/yarn.lock
Labels: Feat 🏃🏻‍♀️

#9 feat: 리스트 헤더 구현
  Client/src/components/list/ListHeader.jsx
  Client/src/pages/List.jsx
Labels: Feat 🏃🏻‍♀️

#10 Gwagjiug
  Client/src/pages/CheckRoutine.jsx
Labels: Feat 🏃🏻‍♀️

#11 Feat: routine list 생성
  Client/public/assets/ic_routine_delete.svg
  Client/public/assets/ic_routine_plus.svg
  Client/public/assets/img_routine_bold_smile.svg
  Client/src/assets/svg/IcRoutineDelete.jsx
  Client/src/assets/svg/IcRoutinePlus.jsx
  Client/src/assets/svg/ImgRoutineBoldSmile.jsx
  Client/src/assets/svg/index.jsx
  Client/src/components/postRoutine/PostRoutine.jsx
  Client/src/pages/PostRoutine.jsx
Labels: Feat 🏃🏻‍♀️

#12 Design: 전체 리스트 카드 컴포넌트 구축
  Client/src/components/list/CardItem.jsx
  Client/src/pages/List.jsx
Labels: Feat 🏃🏻‍♀️

#13 Refacotr: MainContent 컴포넌트 분리
  Client/src/components/main/MainContent.jsx
  Client/src/pages/Main.jsx
Labels: Refactor 💭

#15 Fix: routine list
  Client/src/components/postRoutine/PostRoutine.jsx
  Client/src/pages/Main.jsx
Labels: Fix ⚙️

#14 feat: 리스트 뷰 구현 완성
  Client/src/components/list/CardsSection.jsx
  Client/src/components/list/LevelSection.jsx
  Client/src/components/list/SuccessRateSection.jsx
  Client/src/components/list/cardsection/InfoCard.jsx
  Client/src/components/list/levelsection/LevelDisplay.jsx
  Client/src/components/list/successsection/PercentageDisplay.jsx
  Client/src/pages/List.jsx
  Client/src/styles/theme.js
Labels: Feat 🏃🏻‍♀️

#16 Gwagjiug
  Client/public/assets/ic_checkbox_default.svg
  Client/public/assets/ic_checkbox_disabled.svg
  Client/src/apis/axios.js
  Client/src/assets/svg/IcCheckboxDefault.jsx
  Client/src/assets/svg/IcCheckboxDisabled.jsx
  Client/src/assets/svg/index.jsx
  Client/src/components/check/Button.jsx
  Client/src/components/check/Header.jsx
  Client/src/components/check/Input.jsx
  Client/src/pages/CheckRoutine.jsx
  Client/src/styles/global.js
Labels: Feat 🏃🏻‍♀️

#19 feat: 빡빡이 배열 생성
  Client/public/assets/img_checkbox_hair01.svg
  Client/public/assets/img_checkbox_hair02.svg
  Client/public/assets/img_checkbox_hair03.png
  Client/public/assets/img_checkbox_hair04.svg
  Client/public/assets/img_checkbox_hair05.svg
  Client/public/assets/img_checkbox_hair06.svg
  Client/public/assets/img_checkbox_hair07.svg
  Client/public/assets/img_checkbox_hair08.svg
  Client/src/assets/svg/ImgCheckboxHair01.jsx
  Client/src/assets/svg/ImgCheckboxHair02.jsx
  Client/src/assets/svg/ImgCheckboxHair04.jsx
  Client/src/assets/svg/ImgCheckboxHair05.jsx
  Client/src/assets/svg/ImgCheckboxHair06.jsx
  Client/src/assets/svg/ImgCheckboxHair07.jsx
  Client/src/assets/svg/ImgCheckboxHair08.jsx
  Client/src/assets/svg/index.jsx
  Client/src/const/imgCheckboxHairArray.js
Labels: Feat 🏃🏻‍♀️

#20 Design: Meta Icon 추가
  Client/index.html
  Client/public/assets/Logo.svg
  Client/src/assets/Images/logo.png
  Client/src/assets/svg/Logo.jsx
  Client/src/assets/svg/index.jsx
Labels: Design

#21 feat: 4페이지 api 로직 구현
  Client/src/apis/list/fetchLevelData.js
  Client/src/apis/list/getSuccessRateData.js
  Client/src/components/list/LevelSection.jsx
  Client/src/components/list/successsection/PercentageDisplay.jsx
Labels: Feat 🏃🏻‍♀️

#22 feat: routine list
  Client/package.json
  Client/src/apis/axios.js
  Client/src/components/check/Input.jsx
  Client/src/components/postRoutine/PostRoutine.jsx
  Client/src/pages/Edit.jsx
  Client/src/utils/.keep
  Client/src/utils/getFormattedDate.js
  Client/src/utils/postRoutine.js
  Client/yarn.lock
Labels: Feat 🏃🏻‍♀️
